name: Greetings

on:
  push:
    branches: [ main ]
  issues:
    types: [ opened ]
  pull_request:
    branches: [main]
  pull_request_review_comment:
    types: [ created ]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "<h1>Thank you for setting up an issue. Be sure to include labels and some examples related to the issue</h1>"
          pr-message: "Don't forget to link the issues and a screenshot (if possible) of the work. If you are having errors related to formatting, run `yarn format`."

